"""
scenario_evaluator.py  —  Evaluate trained models on synthetic scenarios
=========================================================================
Runs all existing trained checkpoints on the synthetic scenario datasets
generated by scenario_generator.py. No retraining is required.

For each (model, seed, horizon, scenario) combination, computes:
    - NSE, RMSE, MAE on the full synthetic test set
    - Scenario-specific metrics (POD/FAR, degradation rate, etc.)
    - Degradation ratio vs real-data performance (scenario_rmse / real_rmse)

Reuses load_model() and load_graph() from run_inference.py — no duplication.

Output
------
    results/scenarios/{scenario_name}/model_metrics.json  per scenario
    results/scenarios/scenario_summary.csv                consolidated

Usage
-----
    python src/scenarios/scenario_evaluator.py --all-scenarios --all-models
    python src/scenarios/scenario_evaluator.py --scenario S1 --model gru
    python src/scenarios/scenario_evaluator.py --scenario S2 --horizon 4
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch

# ── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR  = Path(__file__).resolve().parent.parent.parent
PROC_DIR  = BASE_DIR / "dataset/processed"
GRAPH_DIR = BASE_DIR / "dataset/graph"
SCEN_DIR  = BASE_DIR / "dataset/scenarios"
CKPT_ROOT = BASE_DIR / "checkpoints"
RESULTS   = BASE_DIR / "results/scenarios"
RESULTS.mkdir(parents=True, exist_ok=True)

for _p in [BASE_DIR, BASE_DIR / "src"]:
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)

# Import from run_inference.py — reuse without duplication
from run_inference import (  # type: ignore
    load_model,
    load_graph,
    resolve_model_tag,
    CKPT_ROOT as _RI_CKPT_ROOT,
    _kge_per_node,
    _peak_timing_error,
)

STEP_MIN  = 15
F_STAGE   = 0
F_SW2_SAT = 9

SCENARIOS = ["S1_ConvectiveCell", "S2_GaugeFailure",
             "S3_InniscarraRelease", "S4_SatBreakthrough",
             "S5_SpatialGradient", "S6_ChannelBlockage"]

HORIZONS  = [4, 12, 16, 24, 48]


# ══════════════════════════════════════════════════════════════════════════════
# Metric computation helpers
# ══════════════════════════════════════════════════════════════════════════════

def _nse(pred: np.ndarray, target: np.ndarray,
         mask: np.ndarray) -> float:
    m  = mask.astype(bool) & np.isfinite(pred) & np.isfinite(target)
    if m.sum() < 2:
        return float("nan")
    p, t   = pred[m], target[m]
    ss_res = float(np.sum((t - p) ** 2))
    ss_tot = float(np.sum((t - t.mean()) ** 2))
    return 1.0 - ss_res / ss_tot if ss_tot > 1e-12 else float("nan")


def _rmse(pred: np.ndarray, target: np.ndarray,
          mask: np.ndarray) -> float:
    m = mask.astype(bool) & np.isfinite(pred) & np.isfinite(target)
    if m.sum() < 1:
        return float("nan")
    return float(np.sqrt(np.mean((pred[m] - target[m]) ** 2)))


def _pod_far(pred: np.ndarray, target: np.ndarray,
             bankfull: np.ndarray) -> tuple[float, float]:
    """POD and FAR using per-node bankfull thresholds."""
    TP = FP = FN = 0
    for n in range(pred.shape[1]):
        thr = float(bankfull[n])
        obs_flood  = target[:, n] >= thr
        pred_flood = pred[:, n]   >= thr
        TP += int(( obs_flood &  pred_flood).sum())
        FP += int((~obs_flood &  pred_flood).sum())
        FN += int(( obs_flood & ~pred_flood).sum())
    pod = TP / max(TP + FN, 1)
    far = FP / max(TP + FP, 1)
    return pod, far


def compute_scenario_extended_metrics(
    pred: np.ndarray, target: np.ndarray, mask: np.ndarray,
    bankfull: np.ndarray, meta: dict, T_in: int, T_out: int,
) -> dict:
    """
    KGE and peak-timing error for scenario evaluation, reusing
    run_inference.py's _kge_per_node and _peak_timing_error directly
    (both are generic over raw [T,N] arrays with no data-source
    assumption — confirmed by direct inspection before reuse here,
    not reimplemented, so there's no risk of drifting from the
    real-data version's exact formulas).

    KGE is computed on the full pooled (pred, target, mask) — safe to
    pool across windows, since it's a per-node correlation/variability
    statistic, not sensitive to window boundaries.

    Peak-timing error is NOT pooled the same way. _peak_timing_error
    uses a +/-48hr internal search window when matching a predicted
    peak to an observed one -- far larger than a scenario's own
    T_per_window (typically 104 steps = 26hr). Calling it on the full
    concatenated array risks matching an observed peak in one window to
    a "predicted peak" that's actually inside a completely unrelated
    window (different historical base period, different injected
    event). This calls it once PER WINDOW instead, using
    _window_local_step to recover window boundaries -- the same
    per-window isolation principle every s1-s6_metrics function already
    uses for the same underlying reason.

    Aggregation across windows: the pooled MEAN is mathematically exact
    (weighted by each window's own event count -- mean of a union of
    groups equals sum(group_mean*group_n)/sum(group_n) always). The
    pooled MEDIAN is an approximation (median of per-window medians,
    each weighted by event count) -- a true pooled median would need
    the raw per-event errors, which _peak_timing_error does not expose
    without duplicating its internal peak-matching logic. Flagged
    explicitly here and in the returned dict key name rather than
    silently presented as exact.
    """
    print('compute_scenario_extended_metrics')
    kge_results = _kge_per_node(pred, target, mask)
    print(f'compute_scenario_extended_metrics|kge_results: {kge_results}')

    kge_vals   = [r["kge"]   for r in kge_results if not np.isnan(r["kge"])]
    r_vals     = [r["r"]     for r in kge_results if not np.isnan(r["r"])]
    alpha_vals = [r["alpha"] for r in kge_results if not np.isnan(r["alpha"])]

    print(f'compute_scenario_extended_metrics|kge_vals: {kge_vals}')
    print(f'compute_scenario_extended_metrics|r_vals: {r_vals}')
    print(f'compute_scenario_extended_metrics|alpha_vals: {alpha_vals}')

    result = {
        "kge_mean_syn":       round(float(np.mean(kge_vals)),   4) if kge_vals   else float("nan"),
        "kge_r_mean_syn":     round(float(np.mean(r_vals)),     4) if r_vals     else float("nan"),
        "kge_alpha_mean_syn": round(float(np.mean(alpha_vals)), 4) if alpha_vals else float("nan"),
    }

    T_window = meta.get("T_per_window", 104)
    n_rows = pred.shape[0]
    _, window_idx = _window_local_step(n_rows, T_in, T_out, T_window)

    window_means, window_medians, window_counts = [], [], []
    for w in np.unique(window_idx):
        rows = (window_idx == w)
        if rows.sum() < 2:
            continue
        pt = _peak_timing_error(pred[rows], target[rows], mask[rows], bankfull)
        if pt["peak_timing_n_events"] > 0:
            window_means.append(pt["peak_timing_mean_hr"])
            window_medians.append(pt["peak_timing_median_hr"])
            window_counts.append(pt["peak_timing_n_events"])

    total_events = int(sum(window_counts))
    if total_events > 0:
        weights = np.array(window_counts, dtype=float)
        pooled_mean = float(np.average(window_means, weights=weights))
        # Approximate pooled median -- see docstring. Named
        # "_approx" so it isn't mistaken for the exact statistic
        # _peak_timing_error itself reports for real-data evaluation.
        pooled_median_approx = float(np.average(window_medians, weights=weights))
    else:
        pooled_mean = float("nan")
        pooled_median_approx = float("nan")

    result.update({
        "peak_timing_mean_hr_syn":          round(pooled_mean, 4) if total_events else float("nan"),
        "peak_timing_median_hr_syn_approx": round(pooled_median_approx, 4) if total_events else float("nan"),
        "peak_timing_n_events_syn":         total_events,
        "peak_timing_n_windows_with_events_syn": len(window_counts),
    })
    return result

def find_leaf_checkpoints(root_dir):
    checkpoint_root = Path(root_dir)
    checkpoint_dirs = [
        p.parent
        for p in checkpoint_root.rglob("best_model.pt")
    ]
    return checkpoint_dirs

# ══════════════════════════════════════════════════════════════════════════════
# Scenario-specific metrics
# ══════════════════════════════════════════════════════════════════════════════

def _window_local_step(n_rows: int, T_in: int, T_out: int,
                        T_window: int) -> tuple[np.ndarray, np.ndarray]:
    """
    Shared helper for every scenario-specific metric below.

    scenario_generator.py concatenates many independent T_window-length
    windows back-to-back (see e.g. meta["T_per_window"], usually 104).
    Row i of `pred`/`y_syn` (after the target_arr alignment in
    evaluate_checkpoint) corresponds to absolute target time
    (i + T_in + T_out - 1) in that concatenated series — NOT row i of a
    single window. Any per-window-relative quantity (an event step, a
    failure onset, a breakthrough midpoint) must be computed against
    each row's position WITHIN its own window, not against a single
    global cutoff/midpoint over the whole array. Using a global cutoff
    is exactly the bug that made s3_false_alarm_rate come out as exactly
    0.0 for all 135 checkpoints (see s3_metrics docstring) — the same
    class of bug was independently present in s1_metrics, s2_metrics,
    and s4_metrics, just producing plausible-looking-but-wrong numbers
    instead of an obvious zero, which is why it went unnoticed longer.

    Returns (local_step, window_idx), both shape [n_rows].
    """
    abs_t = np.arange(n_rows) + T_in + T_out - 1
    local_step = abs_t % T_window
    window_idx = abs_t // T_window
    return local_step, window_idx


def s1_metrics(pred: np.ndarray, y_syn: np.ndarray,
               meta: dict, T_in: int, T_out: int) -> dict:
    """
    ConvectiveCell: RMSE at downstream (Cork city) nodes specifically
    during the ~12 steps following the expected flood arrival.

    FIXED: previously sliced pred[arrival:T_eval] as a single global
    cutoff over the whole concatenated array, which only ever evaluated
    the FIRST of the ~21 generation windows' flood arrivals (rows
    ~42-54) and silently discarded the other 20 windows' arrival periods
    entirely — understating both the sample size and, if arrival timing
    or model behaviour varies across windows/seeds, potentially biasing
    the result toward whatever happened to be in that one window. This
    version evaluates the arrival window WITHIN EVERY generation window
    and aggregates across all of them, using the same per-window local
    step recovery as s3_metrics.
    """
    downstream = meta.get("downstream_nodes", [])
    pulse_at   = meta.get("pulse_at_step", 34)
    arrival    = pulse_at + 8    # approximate flood wave arrival at downstream
    T_window   = meta.get("T_per_window", 104)

    if not downstream or pred.shape[0] == 0:
        return {"s1_downstream_rmse": float("nan")}

    n_rows = pred.shape[0]
    local_step, _ = _window_local_step(n_rows, T_in, T_out, T_window)
    # 12-step arrival window, evaluated within EVERY generation window,
    # not just the first.
    in_arrival_window = (local_step >= arrival) & (local_step < arrival + 12)

    if in_arrival_window.sum() < 5:
        return {"s1_downstream_rmse": float("nan")}

    p_down = pred[in_arrival_window][:, downstream]
    t_down = y_syn[in_arrival_window][:, downstream]
    m_down = np.ones_like(p_down, dtype=bool)
    return {
        "s1_downstream_rmse": _rmse(p_down, t_down, m_down),
    }


def s2_metrics(pred: np.ndarray, y_syn: np.ndarray,
               meta: dict, real_rmse: float,
               T_in: int, T_out: int) -> dict:
    """
    GaugeFailure: RMSE after failure onset, both pooled across all nodes
    and restricted specifically to the failed nodes themselves.

    FIXED (time alignment): previously sliced pred[t_fail:] as a single
    global cutoff, which only excludes the first ~36 rows of the ENTIRE
    concatenated array (spanning 40 flood-windows x 3 failure_levels =
    120 segments) rather than isolating genuinely post-failure rows
    WITHIN each of the 120 segments — diluting true post-failure steps
    with pre-failure calm steps from every other segment. This version
    isolates post-failure rows per-window using the same local-step
    recovery as s1/s3_metrics.

    FIXED (node scope): the docstring here previously claimed "RMSE at
    downstream nodes", but the implementation never filtered by node at
    all — it pooled ALL 27 nodes together, meaning the 1-5 nodes whose
    sensor actually failed were diluted among the 22-26 completely
    unaffected nodes in every single evaluation. Even total failure to
    predict the corrupted nodes correctly would barely move a pooled
    27-node RMSE. scenario_generator.py's generate_s2_gauge_failure
    computes failed_node_sets during generation but never saves it to
    meta — this version reconstructs which nodes were failed for any
    given row from the deterministic block ordering
    (row = flood_window_idx * len(failure_levels) + failure_level_idx,
    fail_nodes = headwater_idx[:failure_levels[failure_level_idx]]),
    using headwater_idx and failure_levels, both of which ARE saved.

    Both metrics are reported: s2_post_failure_rmse_all (the original,
    pooled — kept for continuity with prior results) and
    s2_post_failure_rmse_failed_nodes (new, the metric this scenario's
    own docstring already claimed to be computing).
    """
    t_fail    = meta.get("t_failure_step", 36)
    T_window  = meta.get("T_per_window", 104)
    headwater_idx = meta.get("headwater_nodes", [])
    failure_levels = meta.get("failure_levels", [])
    n_rows    = pred.shape[0]

    nan_result = {
        "s2_post_failure_rmse_all": float("nan"),
        "s2_post_failure_rmse_failed_nodes": float("nan"),
        "s2_degradation_ratio": float("nan"),
        "s2_degradation_ratio_failed_nodes": float("nan"),
    }
    if n_rows == 0 or not headwater_idx or not failure_levels:
        return nan_result

    local_step, window_idx = _window_local_step(n_rows, T_in, T_out, T_window)
    is_post = local_step >= t_fail

    if is_post.sum() < 5:
        return nan_result

    # Pooled (original) metric, kept for continuity with prior results.
    p_post = pred[is_post]
    t_post = y_syn[is_post]
    m_post = np.ones_like(p_post, dtype=bool)
    rmse_all = _rmse(p_post, t_post, m_post)

    # Node-restricted metric: build a per-row mask selecting only the
    # nodes actually failed in that row's block.
    n_levels = len(failure_levels)
    node_mask = np.zeros_like(pred, dtype=bool)   # [n_rows, N]
    for w in np.unique(window_idx):
        level_idx = int(w) % n_levels
        n_fail = failure_levels[level_idx]
        fail_nodes = headwater_idx[:n_fail]
        rows_in_window = (window_idx == w)
        node_mask[np.ix_(rows_in_window, fail_nodes)] = True

    combined_mask = node_mask & is_post[:, None]
    if combined_mask.sum() < 5:
        rmse_failed = float("nan")
    else:
        rmse_failed = _rmse(pred, y_syn, combined_mask)

    return {
        "s2_post_failure_rmse_all": rmse_all,
        "s2_post_failure_rmse_failed_nodes": rmse_failed,
        "s2_degradation_ratio": (rmse_all / real_rmse
                                 if real_rmse > 0 and np.isfinite(rmse_all) else float("nan")),
        "s2_degradation_ratio_failed_nodes": (rmse_failed / real_rmse
                                              if real_rmse > 0 and np.isfinite(rmse_failed) else float("nan")),
    }


def s3_metrics(pred: np.ndarray, y_syn: np.ndarray,
               meta: dict, bankfull: np.ndarray,
               T_in: int, T_out: int) -> dict:
    """
    InniscarraRelease: does the model correctly react to a legitimate,
    operationally-driven signal that starts at the reservoir outlet and
    is deliberately decoupled from rainfall — while NOT leaking that
    same signal backward onto the reservoir INFLOW gauges, where it has
    no physical influence (water cannot flow upstream through a dam)?

    scenario_generator.py's S3 changed from a hypothetical debris
    blockage (upstream/downstream stage decoupling on an ordinary river
    edge) to a real, documented ESB reservoir release event. The old
    meta fields ("blockage_edge", "t_blockage_step") no longer exist —
    this version reads the new ones ("release_node", "t_release_step",
    "decoupled_nodes", "downstream_nodes") and reports two
    complementary metrics, both restricted to rows genuinely past each
    window's own release onset (per-window local step via
    _window_local_step — a global cutoff over the concatenated array
    would suffer the same aliasing bug documented in s1/s2_metrics'
    predecessors):

      - s3_downstream_rmse_post: RMSE at the propagation-chain nodes
        downstream of the tailrace during genuinely post-release rows.
        This IS a real, physically-driven signal the model should learn
        to anticipate from the release node's own trajectory, not from
        rainfall. Lower is better.
      - s3_upstream_leakage_bias: mean(pred - obs) at the two reservoir
        INFLOW nodes (Inniscarra Headrace, Carrigadrohid Headrace)
        during the same rows. These nodes carry no synthetic
        perturbation at all — obs stays at its natural pre-release
        level — so any systematic rise here is the model spuriously
        routing an outlet-driven signal backward against the hydraulic
        gradient. Should be ~0 for any model that respects reservoir
        topology; a large positive value is the direct analogue of the
        old scenario's "false alarm".
    """
    release    = meta.get("release_node", {})
    t_rel      = meta.get("t_release_step", 36)
    T_window   = meta.get("T_per_window", 104)
    downstream = meta.get("downstream_nodes", [])
    decoupled  = meta.get("decoupled_nodes", {})
    decoupled_idx = [v["idx"] for v in decoupled.values()] if decoupled else []

    if not downstream or pred.shape[0] == 0:
        return {"s3_downstream_rmse_post": float("nan"),
                "s3_upstream_leakage_bias": float("nan")}

    n_rows = pred.shape[0]
    local_step, _ = _window_local_step(n_rows, T_in, T_out, T_window)
    is_post = local_step >= t_rel

    if is_post.sum() < 5:
        return {"s3_downstream_rmse_post": float("nan"),
                "s3_upstream_leakage_bias": float("nan")}

    p_down = pred[is_post][:, downstream]
    t_down = y_syn[is_post][:, downstream]
    m_down = np.ones_like(p_down, dtype=bool)
    downstream_rmse = _rmse(p_down, t_down, m_down)

    if decoupled_idx:
        p_up = pred[is_post][:, decoupled_idx]
        t_up = y_syn[is_post][:, decoupled_idx]
        finite = np.isfinite(p_up) & np.isfinite(t_up)
        leakage_bias = (float(np.mean((p_up - t_up)[finite]))
                        if finite.sum() > 0 else float("nan"))
    else:
        leakage_bias = float("nan")

    return {
        "s3_downstream_rmse_post": (round(downstream_rmse, 5)
                                    if np.isfinite(downstream_rmse) else float("nan")),
        "s3_upstream_leakage_bias": (round(leakage_bias, 5)
                                     if np.isfinite(leakage_bias) else float("nan")),
    }


def s4_metrics(pred: np.ndarray, y_syn: np.ndarray,
               X_syn: np.ndarray, meta: dict,
               T_in: int, T_out: int) -> dict:
    """
    SatBreakthrough: RMSE before and after breakthrough, plus ratio.
    Models that correctly anticipate the breakthrough should have
    lower post-breakthrough RMSE relative to their pre-breakthrough RMSE.

    FIXED: previously used t_bt = T // 2 — the midpoint of the ENTIRE
    concatenated array (30 generation windows x 104 steps = 3120 rows).
    That midpoint (row 1560) falls exactly on a window boundary, so
    rmse_pre was actually computed over windows 0-14 IN THEIR ENTIRETY
    (mixing each window's true pre- AND post-breakthrough segments
    together) and rmse_post over windows 15-29 entirely — this has
    nothing to do with sat_breakthrough_step (meta["sat_breakthrough_step"],
    typically 46 steps into each window — see scenario_generator.py's
    derivation of sat_breakthrough_step from the saturation ramp
    parameters, fixed from an earlier hardcoded T_IN+8 that didn't
    actually coincide with the ramp crossing its own excess_factor
    threshold), despite producing plausible-looking, non-zero numbers.
    This version isolates pre/post-breakthrough rows WITHIN every window
    using the same local-step recovery as s1/s2/s3_metrics.
    """
    t_bt      = meta.get("sat_breakthrough_step", 46)
    T_window  = meta.get("T_per_window", 104)
    n_rows    = pred.shape[0]

    if n_rows == 0:
        return {"s4_rmse_pre_breakthrough":  float("nan"),
                "s4_rmse_post_breakthrough": float("nan"),
                "s4_post_pre_ratio":         float("nan")}

    local_step, _ = _window_local_step(n_rows, T_in, T_out, T_window)
    is_pre  = local_step <  t_bt
    is_post = local_step >= t_bt

    if is_pre.sum() < 5 or is_post.sum() < 5:
        return {"s4_rmse_pre_breakthrough":  float("nan"),
                "s4_rmse_post_breakthrough": float("nan"),
                "s4_post_pre_ratio":         float("nan")}

    mask_a = np.ones((is_pre.sum(),  pred.shape[1]), dtype=bool)
    mask_b = np.ones((is_post.sum(), pred.shape[1]), dtype=bool)
    rmse_pre  = _rmse(pred[is_pre],  y_syn[is_pre],  mask_a)
    rmse_post = _rmse(pred[is_post], y_syn[is_post], mask_b)
    return {
        "s4_rmse_pre_breakthrough":  rmse_pre,
        "s4_rmse_post_breakthrough": rmse_post,
        "s4_post_pre_ratio":         (rmse_post / max(rmse_pre, 1e-6)),
    }


def s6_metrics(pred: np.ndarray, y_syn: np.ndarray,
               meta: dict, T_in: int, T_out: int) -> dict:
    """
    ChannelBlockage: quantifies the architectural blind spot at the
    bridge/culvert backwater location, rather than testing whether a
    model "passes." A large positive s6_upstream_backwater_bias is the
    EXPECTED result for every model — see generate_s6_channel_blockage's
    docstring in scenario_generator.py for why no model in this suite
    has a message-passing pathway to anticipate it.

      - s6_upstream_backwater_bias: mean(obs - pred) at the
        blockage+upstream nodes during genuinely post-blockage rows.
        Positive = model under-predicts the backwater rise it can't see
        coming (the expected failure mode). Near zero would mean the
        model somehow anticipated it, worth investigating why.
      - s6_downstream_suppression_rmse: RMSE at the immediate downstream
        node during the same rows — this one IS potentially learnable
        from the node's own upstream-of-it inputs (rainfall, its own
        recent stage trend) without needing reverse graph edges, so
        unlike the backwater metric, better performance here is a
        real, meaningful comparison across models.

    Uses the same per-window local-step recovery as s1-s4_metrics (see
    _window_local_step) — a global cutoff over the concatenated array
    would misattribute rows across window boundaries.
    """
    blockage = meta.get("blockage_node", {})
    upstream = meta.get("upstream_node", {})
    downstream = meta.get("downstream_node", {})
    t_blk    = meta.get("t_blockage_step", 36)
    T_window = meta.get("T_per_window", 104)

    backwater_idx = [i for i in (blockage.get("idx"), upstream.get("idx"))
                     if i is not None]
    downstream_idx = downstream.get("idx")

    if not backwater_idx or downstream_idx is None or pred.shape[0] == 0:
        return {"s6_upstream_backwater_bias": float("nan"),
                "s6_downstream_suppression_rmse": float("nan")}

    n_rows = pred.shape[0]
    local_step, _ = _window_local_step(n_rows, T_in, T_out, T_window)
    is_post = local_step >= t_blk

    if is_post.sum() < 5:
        return {"s6_upstream_backwater_bias": float("nan"),
                "s6_downstream_suppression_rmse": float("nan")}

    p_bw = pred[is_post][:, backwater_idx]
    t_bw = y_syn[is_post][:, backwater_idx]
    finite = np.isfinite(p_bw) & np.isfinite(t_bw)
    bias = float(np.mean((t_bw - p_bw)[finite])) if finite.sum() > 0 else float("nan")

    p_down = pred[is_post][:, [downstream_idx]]
    t_down = y_syn[is_post][:, [downstream_idx]]
    m_down = np.ones_like(p_down, dtype=bool)
    down_rmse = _rmse(p_down, t_down, m_down)

    return {
        "s6_upstream_backwater_bias": round(bias, 5) if np.isfinite(bias) else float("nan"),
        "s6_downstream_suppression_rmse": (round(down_rmse, 5)
                                           if np.isfinite(down_rmse) else float("nan")),
    }


def s5_metrics(pred: np.ndarray, y_syn: np.ndarray,
               meta: dict) -> dict:
    """
    SpatialGradient: RMSE specifically at the most downstream (eastern) nodes,
    where graph routing is required to carry the western flood signal.
    """
    downstream = meta.get("downstream_nodes", [])
    if not downstream:
        return {"s5_downstream_rmse": float("nan")}
    p_d = pred[:, downstream]
    t_d = y_syn[:, downstream]
    m_d = np.ones_like(p_d, dtype=bool)
    return {"s5_downstream_rmse": _rmse(p_d, t_d, m_d)}


# ══════════════════════════════════════════════════════════════════════════════
# Core inference on synthetic array
# ══════════════════════════════════════════════════════════════════════════════

@torch.no_grad()
def run_on_scenario(
    model:    torch.nn.Module,
    tag:      str,
    hp:       dict,
    X_syn:    np.ndarray,   # [T_s, N, F]
    y_syn:    np.ndarray,   # [T_s, N]
    m_syn:    np.ndarray,   # [T_s, N]
    T_in:     int,
    T_out:    int,
    device:   torch.device,
) -> np.ndarray:
    """
    Slide a T_in-step window over the synthetic time series, run the model
    forward, and return predictions at step T_out-1 as [n_windows, N].
    """
    ei, ea, na = load_graph(device)

    needs_graph = tag not in ("gru", "lstm", "ealstm", "dfc_gnn", "dfc_gnn_unified")
    if not needs_graph:
        ei, ea = None, None
    if tag in ("dfc_gnn", "dfc_gnn_unified"):
        na = None

    T_s = X_syn.shape[0]
    N   = X_syn.shape[1]
    F   = X_syn.shape[2]

    # Build node_attr tensor (z-score using real dataset stats for consistency)
    import pandas as _pd
    nd_df = pd.read_csv(GRAPH_DIR / "nodes.csv")
    node_cols = ["log_catchment_area_km2", "gauge_datum_mOSGM15", "p90_mAOD",
                 "amax_med_mAOD", "is_reservoir", "is_tidal", "has_discharge"]
    na_raw = torch.tensor(nd_df[node_cols].values, dtype=torch.float32)
    na_real = (na_raw - na_raw.mean(0)) / na_raw.std(0).clamp(min=1e-6)
    if na is not None:
        na = na_real.to(device)

    preds = []
    stride = 1
    for t in range(0, T_s - T_in - T_out + 1, stride):
        x_np   = X_syn[t : t + T_in]          # [T_in, N, F]
        x_t    = torch.tensor(x_np, dtype=torch.float32).unsqueeze(0).to(device)
        # x_t: [1, T_in, N, F]

        if tag in ("dfc_gnn", "dfc_gnn_unified"):
            output = model(x_t)
            delta  = output[0] if isinstance(output, (tuple, list)) else output
        elif needs_graph:
            delta = model(x_t, na, ei, ea)
        else:
            delta = model(x_t, na)

        last_obs = x_t[:, -1, :, F_STAGE]         # [1, N]
        abs_pred = delta[:, T_out - 1, :] + last_obs  # [1, N]
        preds.append(abs_pred.detach().cpu().numpy()[0])  # [N]

    return np.stack(preds, axis=0) if preds else np.zeros((0, N))


# ══════════════════════════════════════════════════════════════════════════════
# Per-checkpoint evaluation
# ══════════════════════════════════════════════════════════════════════════════

def evaluate_checkpoint(ckpt_dir: Path, scen_dir: Path,
                        device: torch.device,
                        bankfull: np.ndarray) -> dict | None:
    """
    Load one checkpoint, run it on the synthetic scenario, compute metrics.
    Returns a flat dict of results suitable for a CSV row.
    """
    tag = resolve_model_tag(ckpt_dir)
    rel = ckpt_dir.relative_to(CKPT_ROOT)
    parts = rel.parts
    if len(parts) < 3:
        return None
    try:
        seed   = int(parts[1])
        T_out  = int(parts[2])
    except (ValueError, IndexError):
        return None

    # Load scenario arrays
    X_syn = np.load(scen_dir / "X_synthetic.npy")
    y_syn = np.load(scen_dir / "y_synthetic.npy")
    m_syn = np.load(scen_dir / "mask_synthetic.npy")
    with open(scen_dir / "scenario_meta.json") as f:
        meta = json.load(f)

    # Load model weights
    try:
        model, hp = load_model(ckpt_dir, device)
    except Exception as e:
        print(f"    [skip] load_model failed for {ckpt_dir.name}: {e}")
        return None

    T_in = hp.get("t_in", 32)

    try:
        pred = run_on_scenario(
            model, tag, hp, X_syn, y_syn, m_syn,
            T_in=T_in, T_out=T_out, device=device)
    except Exception as e:
        print(f"    [skip] inference failed: {e}")
        return None

    # Guard against scenarios shorter than this checkpoint's T_in+T_out
    # requirement. run_on_scenario() already returns an empty (0, N) array
    # in that case rather than raising — but without this check, the
    # np.stack() calls below crash with "need at least one array to
    # stack", and since this whole function is called from main() with no
    # surrounding try/except, that crash kills the ENTIRE sweep instead of
    # skipping just this one (model, seed, horizon) combination.
    n_windows = pred.shape[0]
    if n_windows == 0:
        min_len_needed = T_in + T_out
        print(f"    [skip] scenario series too short for this checkpoint: "
              f"needs >= {min_len_needed} steps (T_in={T_in} + T_out={T_out}), "
              f"got {len(y_syn)} steps in {scen_dir.name}")
        return None

    # Align predictions to targets
    # Target: y at T_out-1 steps ahead of each window start
    target_arr = np.stack([
        y_syn[t + T_in + T_out - 1]
        for t in range(n_windows)
        if t + T_in + T_out - 1 < len(y_syn)
    ], axis=0)  # [n_windows, N]
    mask_arr = np.stack([
        m_syn[t + T_in + T_out - 1]
        for t in range(n_windows)
        if t + T_in + T_out - 1 < len(y_syn)
    ], axis=0)

    # Second guard: n_windows > 0 doesn't guarantee the filtered list above
    # is non-empty — e.g. if T_in/T_out reported by run_on_scenario ever
    # drifted out of sync with the T_in/T_out used inside this function
    # (they shouldn't, since both come from the same hp/T_out, but this
    # keeps the two np.stack() calls from being the only thing standing
    # between a subtle inconsistency and a full-sweep crash).
    if target_arr.shape[0] == 0:
        print(f"    [skip] no valid (window, target) pairs after alignment "
              f"for {scen_dir.name}")
        return None

    pred = pred[:len(target_arr)]
    # Global metrics on synthetic data
    nse  = _nse(pred,  target_arr, mask_arr)
    rmse = _rmse(pred, target_arr, mask_arr)
    pod, far = _pod_far(pred, target_arr, bankfull)
    extended = compute_scenario_extended_metrics(
        pred, target_arr, mask_arr, bankfull, meta, T_in, T_out)

    # Real-data RMSE for degradation ratio
    real_rmse = float("nan")
    real_metrics_path = ckpt_dir / "test_metrics.json"
    if real_metrics_path.exists():
        with open(real_metrics_path) as f:
            real_rmse = float(json.load(f).get("rmse", float("nan")))

    result = {
        "scenario":   meta["name"],
        "model":      tag,
        "seed":       seed,
        "horizon":    T_out,
        "nse_syn":    round(nse,  4) if np.isfinite(nse)  else None,
        "rmse_syn":   round(rmse, 4) if np.isfinite(rmse) else None,
        "pod_syn":    round(pod,  4),
        "far_syn":    round(far,  4),
        "real_rmse":  round(real_rmse, 4) if np.isfinite(real_rmse) else None,
        "degradation_ratio": round(rmse / real_rmse, 3)
            if (np.isfinite(rmse) and np.isfinite(real_rmse) and real_rmse > 0)
            else None,
        **extended,
    }

    # Scenario-specific extras
    scen_id = meta["name"][:2]
    if scen_id == "S1":
        result.update(s1_metrics(pred, target_arr, meta, T_in, T_out))
    elif scen_id == "S2":
        result.update(s2_metrics(pred, target_arr, meta, real_rmse, T_in, T_out))
    elif scen_id == "S3":
        result.update(s3_metrics(pred, target_arr, meta, bankfull, T_in, T_out))
    elif scen_id == "S4":
        result.update(s4_metrics(pred, target_arr, X_syn, meta, T_in, T_out))
    elif scen_id == "S5":
        result.update(s5_metrics(pred, target_arr, meta))
    elif scen_id == "S6":
        result.update(s6_metrics(pred, target_arr, meta, T_in, T_out))

    return result


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Evaluate trained models on synthetic scenarios")
    parser.add_argument("--all-scenarios", action="store_true")
    parser.add_argument("--all-models",    action="store_true")
    parser.add_argument("--scenario",  type=str, default=None,
                        help="Scenario name or ID (e.g. S1, S1_ConvectiveCell)")
    parser.add_argument("--model",     type=str, default=None,
                        help="Model tag (e.g. gru, st_gnn_hand_edge)")
    parser.add_argument("--horizon",   type=int, default=None,
                        help="Evaluate only this T_out horizon")
    parser.add_argument("--force",     action="store_true",
                        help="Re-evaluate even if results already exist")
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Determine which scenarios to run
    if args.all_scenarios:
        scen_names = SCENARIOS
    elif args.scenario:
        # Accept short form (S1) or full name
        scen_names = [s for s in SCENARIOS
                      if s.startswith(args.scenario) or
                      s == args.scenario]
        if not scen_names:
            print(f"Unknown scenario '{args.scenario}'. "
                  f"Available: {SCENARIOS}")
            return
    else:
        parser.error("Specify --all-scenarios or --scenario NAME")

    # Load bankfull thresholds
    with open(GRAPH_DIR / "bankfull_thresholds.json") as f:
        bf_raw = json.load(f)
    bf_dict = bf_raw.get("thresholds", bf_raw)
    import pandas as pd
    nd = pd.read_csv(GRAPH_DIR / "nodes.csv")
    refs = [str(r) for r in nd["ref"].tolist()]
    bankfull = np.array([float(bf_dict.get(r, 0.5)) for r in refs],
                        dtype=np.float32)

    # Collect checkpoints
    all_ckpts = find_leaf_checkpoints(CKPT_ROOT)
    if args.model:
        all_ckpts = [c for c in all_ckpts
                     if resolve_model_tag(c) == args.model]
    if args.horizon:
        all_ckpts = [c for c in all_ckpts
                     if c.name == str(args.horizon)]
    print(f"Checkpoints to evaluate: {len(all_ckpts)}")

    all_rows: list[dict] = []

    for scen_name in scen_names:
        scen_dir = SCEN_DIR / scen_name
        if not (scen_dir / "X_synthetic.npy").exists():
            print(f"\n[skip] {scen_name}: scenario data not found. "
                  f"Run scenario_generator.py first.")
            continue

        print(f"\n{'='*55}")
        print(f"Evaluating: {scen_name}  ({len(all_ckpts)} checkpoints)")
        print(f"{'='*55}")

        scen_results_dir = RESULTS / scen_name
        scen_results_dir.mkdir(parents=True, exist_ok=True)
        rows = []

        for i, ckpt_dir in enumerate(all_ckpts):
            tag   = resolve_model_tag(ckpt_dir)
            rel   = ckpt_dir.relative_to(CKPT_ROOT)
            label = str(rel)

            # Cache check
            cache_path = scen_results_dir / f"{label.replace('/', '_')}.json"
            if cache_path.exists() and not args.force:
                with open(cache_path) as f:
                    row = json.load(f)
                rows.append(row)
                continue
            print(f"  [{i+1:3d}/{len(all_ckpts)}] {label} … ", end="", flush=True)
            try:
                print('evaluating checkpoints...')
                row = evaluate_checkpoint(ckpt_dir, scen_dir, device, bankfull)
            except Exception as e:
                # Belt-and-braces: evaluate_checkpoint() already catches
                # the failure modes we know about (model load, inference,
                # empty-window alignment) and returns None for those. This
                # catches anything else so one bad checkpoint can't take
                # down the remaining ~130 in the sweep.
                print(f"FAILED (unhandled: {type(e).__name__}: {e})")
                row = None
            if row:
                rows.append(row)
                all_rows.append(row)
                cache_path.parent.mkdir(parents=True, exist_ok=True)
                with open(cache_path, "w") as f:
                    json.dump(row, f)
                print(f"NSE={row.get('nse_syn', 'nan'):.4f}  "
                      f"RMSE={row.get('rmse_syn', 'nan'):.4f}")
            else:
                print("FAILED")

        # Save per-scenario results
        if rows:
            df_scen = pd.DataFrame(rows)
            df_scen.to_csv(scen_results_dir / "model_metrics.csv", index=False)
            print(f"  Saved: {scen_results_dir / 'model_metrics.csv'} "
                  f"({len(rows)} rows)")

    # Save consolidated CSV
    if all_rows:
        df_all = pd.DataFrame(all_rows)
        out_csv = RESULTS / "scenario_summary.csv"
        df_all.to_csv(out_csv, index=False)
        print(f"\nConsolidated: {out_csv} ({len(all_rows)} rows)")


if __name__ == "__main__":
    main()
